import { KeyEnum } from '@effitor/shared'

/** 支持快捷键的实体键名(KeyboardEvent.code) */
// export const Key: typeof KeyEnum = {
//   A: KeyEnum.A,
//   B: KeyEnum.B,
//   C: KeyEnum.C,
//   D: KeyEnum.D,
//   E: KeyEnum.E,
//   F: KeyEnum.F,
//   G: KeyEnum.G,
//   H: KeyEnum.H,
//   I: KeyEnum.I,
//   J: KeyEnum.J,
//   K: KeyEnum.K,
//   L: KeyEnum.L,
//   M: KeyEnum.M,
//   N: KeyEnum.N,
//   O: KeyEnum.O,
//   P: KeyEnum.P,
//   Q: KeyEnum.Q,
//   R: KeyEnum.R,
//   S: KeyEnum.S,
//   T: KeyEnum.T,
//   U: KeyEnum.U,
//   V: KeyEnum.V,
//   W: KeyEnum.W,
//   X: KeyEnum.X,
//   Y: KeyEnum.Y,
//   Z: KeyEnum.Z,

//   F1: KeyEnum.F1,
//   F2: KeyEnum.F2,
//   F3: KeyEnum.F3,
//   F4: KeyEnum.F4,
//   F5: KeyEnum.F5,
//   F6: KeyEnum.F6,
//   F7: KeyEnum.F7,
//   F8: KeyEnum.F8,
//   F9: KeyEnum.F9,
//   F10: KeyEnum.F10,
//   F11: KeyEnum.F11,
//   F12: KeyEnum.F12,

//   Digit0: KeyEnum.Digit0,
//   Digit1: KeyEnum.Digit1,
//   Digit2: KeyEnum.Digit2,
//   Digit3: KeyEnum.Digit3,
//   Digit4: KeyEnum.Digit4,
//   Digit5: KeyEnum.Digit5,
//   Digit6: KeyEnum.Digit6,
//   Digit7: KeyEnum.Digit7,
//   Digit8: KeyEnum.Digit8,
//   Digit9: KeyEnum.Digit9,

//   Escape: KeyEnum.Escape,
//   Backquote: KeyEnum.Backquote,

//   Tab: KeyEnum.Tab,
//   Space: KeyEnum.Space,
//   Enter: KeyEnum.Enter,
//   Backspace: KeyEnum.Backspace,
//   Delete: KeyEnum.Delete,

//   Minus: KeyEnum.Minus,
//   Equal: KeyEnum.Equal,
//   BracketLeft: KeyEnum.BracketLeft,
//   BracketRight: KeyEnum.BracketRight,
//   Backslash: KeyEnum.Backslash,
//   Semicolon: KeyEnum.Semicolon,
//   Quote: KeyEnum.Quote,
//   Comma: KeyEnum.Comma,
//   Period: KeyEnum.Period,
//   Slash: KeyEnum.Slash,

//   ArrowDown: KeyEnum.ArrowDown,
//   ArrowLeft: KeyEnum.ArrowLeft,
//   ArrowRight: KeyEnum.ArrowRight,
//   ArrowUp: KeyEnum.ArrowUp,

//   // 小键盘按键
//   // NumLock: KeyEnum.//,
//   NumpadEqual: KeyEnum.NumpadEqual,
//   NumpadDivide: KeyEnum.NumpadDivide,
//   NumpadMultiply: KeyEnum.NumpadMultiply,
//   NumpadSubtract: KeyEnum.NumpadSubtract,
//   NumpadAdd: KeyEnum.NumpadAdd,
//   NumpadEnter: KeyEnum.NumpadEnter,
//   NumpadDecimal: KeyEnum.NumpadDecimal,
//   Numpad0: KeyEnum.Numpad0,
//   Numpad1: KeyEnum.Numpad1,
//   Numpad2: KeyEnum.Numpad2,
//   Numpad3: KeyEnum.Numpad3,
//   Numpad4: KeyEnum.Numpad4,
//   Numpad5: KeyEnum.Numpad5,
//   Numpad6: KeyEnum.Numpad6,
//   Numpad7: KeyEnum.Numpad7,
//   Numpad8: KeyEnum.Numpad8,
//   Numpad9: KeyEnum.Numpad9,

//   Home: KeyEnum.Home,
//   End: KeyEnum.End,
//   PageUp: KeyEnum.PageUp,
//   PageDown: KeyEnum.PageDown,
// } as const

export type Key = `${KeyEnum}`

/**
 * 快捷键按键需要简化展示的按键, 通过keyboardEvent.code 提取,
 * 如将 BracketLeft 展示为 `[`, 将 ArrowLeft 展示为 `←`
 */
export const keyChars = {
  // export const keyChars: Partial<Record<KeyboardCodeEnum, string>> = {
  KeyA: 'A',
  KeyB: 'B',
  KeyC: 'C',
  KeyD: 'D',
  KeyE: 'E',
  KeyF: 'F',
  KeyG: 'G',
  KeyH: 'H',
  KeyI: 'I',
  KeyJ: 'J',
  KeyK: 'K',
  KeyL: 'L',
  KeyM: 'M',
  KeyN: 'N',
  KeyO: 'O',
  KeyP: 'P',
  KeyQ: 'Q',
  KeyR: 'R',
  KeyS: 'S',
  KeyT: 'T',
  KeyU: 'U',
  KeyV: 'V',
  KeyW: 'W',
  KeyX: 'X',
  KeyY: 'Y',
  KeyZ: 'Z',

  // 那个[倒过来的字符
  Space: '␣', // \u2423
  Backquote: '`',
  Minus: '-',
  Equal: '=',
  BracketLeft: '[',
  BracketRight: ']',
  Backslash: '\\',
  Semicolon: ':',
  Quote: '\'',
  Comma: ',',
  Period: '.',
  Slash: '/',
  ArrowUp: '↑',
  ArrowDown: '↓',
  ArrowLeft: '←',
  ArrowRight: '→',
} as const
