export type { CaretRange, EtPosition } from './config'
export { cr } from './cr'
export type { EtCaret } from './EtCaret'
export type { EtRange } from './EtRange'
export type { EtSelection } from './EtSelection'
export type { SpanRange } from './SpanRange'
